# Generated by Django 4.2.7 on 2025-06-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=4)),
                ('week', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
